### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by imMarkdeVries** [dutchgrit/afascli#2]
Hi Lucas,

I have a request.  I generate all connectors when there will be only few changes. 
As a result my GIT changes bloat due to this line
// Autogenerated on : 20-5-2021 16:08:56 by afas-cli

Is it possible to remove the timestamp  ( default or with an option or so ),  
// Autogenerated by afas-cli
So I don't have to check all connectors for changes due to the timestamp on all

Kind regards Mark

oftewel groetjes ;) fijn weekend

**Comment by LucasVos** [comment]
That makes sense. So, no problem. 
I applied the change as requested (by default, no option).

Upgrade the **afas-cli** tool with
```
dotnet tool update afas-cli --global
```

**Comment by LucasVos** [comment]
Please standby. The Github Action runner is not working correctly 😞  
Will fix it tomorrow.

**Comment by LucasVos** [comment]
Please update to the 1.0.33 version of Afas-Cli for the requested feature.
