### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by imMarkdeVries** [dutchgrit/afascli#3]
Hi Lucas,

I have a small but maybe usefull feature request. 
Is it possible to add an attribute to the generated code (EmitGetConnector) to also add an attribute "description" to a generated field. The content would be the same as the summary comment
This makes it possible to adress it programmatically. 
In my case to add extended properties to a database.

Regards,

Mark

Like this:

        /// <summary>
        /// ClusterIdNaamOmschrijving
        /// </summary>
        [Description("ClusterIdNaamOmschrijving")]
        [JsonProperty("ClusterIdNaam")]
        public virtual string ClusterIdNaam { get; set; }

#for your convenience
 [AttributeUsage(AttributeTargets.Property)]
    public class DescriptionAttribute : Attribute
    {
        string value;

        public DescriptionAttribute(string id)
        {
            this.value = id;
        }

        public string Value
        {
            get { return this.value; }
        }
    }

**Comment by LucasVos** [comment]
Changed as requested, but I used the kind-of built-in [Description attribute ](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute?view=net-5.0) instead. 

Update the tool with: 

`dotnet tool update afas-cli --global --no-cache`
