### ISSUE TITLE
Multiple KeyFields are generated for UpdateConnector KnDimCode (Duplicate KeyFields not allowed)

### ISSUE THREAD

**Issue by nielsverkaart** [dutchgrit/afascli#4]
Hi Lucas,

I've added UpdateConnector KnDimCode (Code verbijzondering) and the generator creates two KeyField attributes. This is not allowed. 

What is your recommendation?

Best regards,
Niels

**Comment by LucasVos** [comment]
Thank you for the report. I see it... It's a bug indeed. 
I think you are the first one to use an UpdateConnector with multiple key's. I need to fix something. Let you know when it's done.

**Comment by LucasVos** [comment]
Issue is fixed. Please update your solution to use the latest `DutchGrit.AfasClient` nuget package (currently 1.0.0.60) . 

Sample usage

``` cs
//Sample to INSERT a new 'VerbijzonderingsAs' in Afas.
var kn = new KnDimCode();
kn.AxId = "2";
kn.VbCo = "TEST";
kn.Ds = "Test description";
var result = client.Save(kn);

if (!result.IsSuccess)
    {
	//handle the error, etc.
    }

//Sample to UPDATE an existing record
var kn2 = new KnDimCode();
kn2.AxId = "2";
kn2.VbCo = "TEST";
kn2.Ds = "Test description (changed)";
result = client.Update(kn)
```

**Comment by nielsverkaart** [comment]
Great, it works!
Thanks for the fast response and fix.
Best regards,
Niels
