### ISSUE TITLE
feature request: choose namespace

### ISSUE THREAD

**Issue by coenm** [dutchgrit/afascli#6]
Hi Lucas,

I have a small feature request:
Is it possible to add an additional argument to the generate command to specify the namespace for the generated code?

**Comment by LucasVos** [comment]
Yes. Update to the latest version of the tool and see `afas-cli generate --help` for more instructions.

**Comment by coenm** [comment]
Thank you for your quick fix. One minor fix;

when I choose my own namespace (ie. 'A.B.C'), then I need an additional using statement because of the interface `IUpdateEntity`

```cs
using DutchGrit.Afas;
```

**Comment by LucasVos** [comment]
Ofcourse... Fixed in the latest release.

**Comment by coenm** [comment]
@LucasVos  Are you sure? 
Installing the latest won't solve this issue. Also, using version 1.0.38 will result in using version 1.0.37.
