### ISSUE TITLE
feature request : internal versus public classes

### ISSUE THREAD

**Issue by coenm** [dutchgrit/afascli#7]
Hi Lucas,

At this moment, the generated model classes are public. Is it possible to add a configuration whether to make generated classes public or internal?

Thanks

**Comment by LucasVos** [comment]
Hi @coenm ! 
Good suggestion. I will put it on the backlog :-)

**Comment by LucasVos** [comment]
Should work in the latest version. 
You can update with  `dotnet tool update afas-cli --global` .
See `afas-cli generate --help' for the instructions.

**Comment by coenm** [comment]
Thanks! It works.
